// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrvbdvezrzwmilwzalqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpydmJkdmV6cnp3bWlsd3phbHF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NDg3OTIsImV4cCI6MjA2MDUyNDc5Mn0.bE1GBzRx3dN9FdcbPy8t71eRuZ7-pBlSerxSrQmjP-g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);